[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plasmetheus"
authors = [{name = "LucianSpitzner", email = "lucian.spitzner@posteo.net"}]
dynamic = ["version", "description"]
