name: plasm
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python=3.11.4
  - numpy
  - h5py
  - pandas
  - matplotlib
  - tqdm
  - ipykernel
  - cookiecutter
  - gitpython
  - sphinx=7.1.2
  - sphinx-rtd-theme=1.3.0rc1
